### ISSUE TITLE
Throws error in release mode on IOS

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [andpor/react-native-sqlite-storage#338]
Trying to use this module for my project. In debug scheme all is ok. Works as expected. But when i build it with release scheme and launch on device I get this error.

2019-03-12 17:12:18.400 [error][tid:com.facebook.react.JavaScript] t.apply is not a function. (In 't.apply(void 0,arguments)', 't.apply' is undefined)
2019-03-12 17:12:18.401939+0300 myApp [2483:827824] t.apply is not a function. (In 't.apply(void 0,arguments)', 't.apply' is undefined)
2019-03-12 17:12:18.405 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: t.apply is not a function. (In 't.apply(void 0,arguments)', 't.apply' is undefined)
2019-03-12 17:12:18.405590+0300 myApp[2483:827829] Unhandled JS Exception: t.apply is not a function. (In 't.apply(void 0,arguments)', 't.apply' is undefined)
2019-03-12 17:12:18.419420+0300 myApp[2483:827829] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: t.apply is not a function. (In 't.apply(void 0,arguments)', 't.apply' is undefined)', reason: 'Unhandled JS Exception: t.apply is not a function. (In 't.apply(void 0,arguments)', 't.apply' is undefined), stack:
<unknown>@486:284
o@469:268
default@493:229
<unknown>@342:345
v@2:1483
<unknown>@11:58
v@2:1483
d@2:866
global code@1489:4
'
*** First throw call stack:
(0x196308ec4 0x1954d9a40 0x100bdf1c8 0x100bdb5d0 0x196310630 0x1961ee450 0x1961ef034 0x100bf33c8 0x100c3a208 0x100c39f64 0x101273824 0x101274dc8 0x10127ce6c 0x10127db60 0x101287bfc 0x195f250dc 0x195f27cec)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

I do build with xcode Version 10.1 (10B61), react-native : "0.57.8"

**Comment by skurgansky-sugarcrm** [comment]
looks like its my project's settings issue.

**Comment by skurgansky-sugarcrm** [comment]
found out that `react-native link` in case of this sqlite-storage adds ref in podfile when README.md says that it should be linked different way. Please update your README.md
